### ISSUE TITLE
Missing variable definition

### ISSUE THREAD

**Issue by SamuGallo** [libretro/skeletor#3]
file: libretro.c
in function audio_callback()

line 165:

M_PI is not defined

**Comment by gouchi** [comment]
Hi,

`M_PI` is coming from [math.h](https://github.com/libretro/skeletor/blob/149b81a51956abe8f5ef27ee0a36a32fab1ce673/libretro.c#L6).

So please close this issue.

Thank you.

[Source](https://www.gnu.org/software/libc/manual/html_node/Mathematical-Constants.html)

**Comment by SamuGallo** [comment]
Thank you

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
